<?php

    $field_prefix = 'field_site_callout_';
    
    acf_add_local_field_group(array(
      'key' => 'group_site_callout',
      'title' => 'Content (Callout)',
      'fields' => array(
        array(
          'key' => $field_prefix . 'column_one',
          'label' => 'Column one',
          'name' => 'column_one',
          'type' => 'wysiwyg',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'default_value' => '',
          'tabs' => 'all',
          'toolbar' => '',
          'media_upload' => 0,
          'delay' => 0,
        ),
        array(
          'key' => $field_prefix . 'column_two',
          'label' => 'Column two',
          'name' => 'column_two',
          'type' => 'wysiwyg',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'default_value' => '',
          'tabs' => 'all',
          'toolbar' => '',
          'media_upload' => 0,
          'delay' => 0,
        ),
        array(
          'key' => $field_prefix . 'buttons',
          'label' => 'Buttons',
          'name' => 'buttons',
          'type' => 'repeater',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'collapsed' => '',
          'min' => 0,
          'max' => 0,
          'layout' => 'block',
          'button_label' => '',
          'sub_fields' => array(
            array(
              'key' => $field_prefix . 'link',
              'label' => 'Link',
              'name' => 'link',
              'aria-label' => '',
              'type' => 'link',
              'instructions' => '',
              'required' => 1,
              'conditional_logic' => 0,
              'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'return_format' => 'array',
            ),
            array(
              'key' => $field_prefix . 'style',
              'label' => 'Style',
              'name' => 'style',
              'type' => 'select',
              'instructions' => '',
              'required' => 1,
              'conditional_logic' => 0,
              'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'choices' => array(
                'pop-purple' => 'Purple',
                'black' => 'Black',
              ),
              'default_value' => false,
              'allow_null' => 0,
              'multiple' => 0,
              'ui' => 0,
              'return_format' => 'value',
              'ajax' => 0,
              'placeholder' => '',
            ),
            array(
              'key' => $field_prefix . 'additional_classes',
              'label' => 'Additional classes',
              'name' => 'additional_classes',
              'type' => 'text',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'default_value' => '',
              'placeholder' => '',
              'prepend' => '',
              'append' => ''
            ),
          ),
        ),
      ),
      'location' => array(
        array(
          array(
            'param' => 'post_type',
            'operator' => '==',
            'value' => 'site_callout',
          ),
        ),
      ),
      'menu_order' => 0,
      'position' => 'normal',
      'style' => 'seamless',
      'label_placement' => 'top',
      'instruction_placement' => 'label',
      'hide_on_screen' => '',
      'active' => true,
      'description' => '',
      'show_in_rest' => 0,
    ));