<?php

	$field_prefix = 'field_site_form_';
	$layout_prefix = 'layout_site_form_';
	
	acf_add_local_field_group(array(
		'key' => 'group_site_form',
		'title' => 'Detail',
		'fields' => array(
			array(
				'key' => $field_prefix . 'rows_tab',
				'label' => 'Rows',
				'name' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
				'endpoint' => 0,
			),
			array(
				'key' => $field_prefix . 'rows',
				'label' => 'Rows',
				'name' => 'rows',
				'type' => 'flexible_content',
				'instructions' => '',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'layouts' => array(
					($layout_prefix . 'text') => array(
						'key' => $layout_prefix . 'text',
						'name' => 'text',
						'label' => 'Text',
						'display' => 'block',
						'sub_fields' => array(
							array(
								'key' => $field_prefix . 'text_label',
								'label' => 'Label',
								'name' => 'label',
								'type' => 'text',
								'instructions' => '',
								'required' => 1,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '100',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
							),
							array(
								'key' => $field_prefix . 'text_type',
								'label' => 'Type',
								'name' => 'type',
								'type' => 'select',
								'instructions' => '',
								'required' => 1,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'choices' => array(
									'single' => 'Single line',
									'multi' => 'Multi line',
									'email' => 'Email',
									'telephone' => 'Telephone',
									'name' => 'Name'
								),
								'default_value' => false,
								'allow_null' => 0,
								'multiple' => 0,
								'ui' => 0,
								'return_format' => 'value',
								'translations' => 'copy_once',
								'ajax' => 0,
								'placeholder' => '',
							),
							array(
								'key' => $field_prefix . 'text_required',
								'label' => 'Required',
								'name' => 'required',
								'type' => 'true_false',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'message' => '',
								'default_value' => 0,
								'ui' => 1,
								'ui_on_text' => '',
								'ui_off_text' => '',
								'translations' => 'copy_once',
							),
							array(
								'key' => $field_prefix . 'text_autocomplete_attribute',
								'label' => 'Autocomplete attribute',
								'name' => 'autocomplete_attribute',
								'type' => 'text',
								'instructions' => '<a href="https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete" target="_blank">Autocomplete attribute information</a>',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
							),
							array(
								'key' => $field_prefix . 'text_error',
								'label' => 'Error message',
								'name' => 'error',
								'type' => 'text',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => array(
									array(
										array(
											'field' => $field_prefix . 'text_type',
											'operator' => '!=',
											'value' => 'email',
										),
										array(
											'field' => $field_prefix . 'text_required',
											'operator' => '==',
											'value' => 1,
										),
									),
								),
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
							),
						),
						'min' => '',
						'max' => '',
					),
					// ($layout_prefix . 'checkbox') => array(
					// 	'key' => $layout_prefix . 'checkbox',
					// 	'name' => 'checkbox',
					// 	'label' => 'Checkbox',
					// 	'display' => 'block',
					// 	'sub_fields' => array(
					// 		array(
					// 			'key' => $field_prefix . 'checkbox_label',
					// 			'label' => 'Label',
					// 			'name' => 'label',
					// 			'type' => 'text',
					// 			'instructions' => '',
					// 			'required' => 1,
					// 			'conditional_logic' => 0,
					// 			'wrapper' => array(
					// 				'width' => '100',
					// 				'class' => '',
					// 				'id' => '',
					// 			),
					// 			'default_value' => '',
					// 			'placeholder' => '',
					// 			'prepend' => '',
					// 			'append' => '',
					// 			'maxlength' => '',
					// 		),
					// 		array(
					// 			'key' => $field_prefix . 'checkbox_required',
					// 			'label' => 'Required',
					// 			'name' => 'required',
					// 			'type' => 'true_false',
					// 			'instructions' => '',
					// 			'required' => 0,
					// 			'conditional_logic' => 0,
					// 			'wrapper' => array(
					// 				'width' => '',
					// 				'class' => '',
					// 				'id' => '',
					// 			),
					// 			'message' => '',
					// 			'default_value' => 0,
					// 			'ui' => 1,
					// 			'ui_on_text' => '',
					// 			'ui_off_text' => '',
					// 		),
					// 	),
					// 	'min' => '',
					// 	'max' => '',
					// ),
				),
				'button_label' => 'Add Row',
				'min' => 1,
				'max' => '',
			),
			array(
				'key' => $field_prefix . 'settings_tab',
				'label' => 'Settings',
				'name' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
				'endpoint' => 0,
			),
			array(
				'key' => $field_prefix . 'button_text',
				'label' => 'Button text',
				'name' => 'button_text',
				'type' => 'text',
				'instructions' => 'If left blank, this will default to "Submit".',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => $field_prefix . 'success_message',
				'label' => 'Success message',
				'name' => 'success_message',
				'type' => 'text',
				'instructions' => 'The message that is shown to a user on successful form submission.',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => $field_prefix . 'email_recipients',
				'label' => 'Email recipients',
				'name' => 'email_recipients',
				'type' => 'text',
				'instructions' => 'Comma separated list of emails that should receive submissions via this form.',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => $field_prefix . 'email_subject',
				'label' => 'Email subject',
				'name' => 'email_subject',
				'type' => 'text',
				'instructions' => 'The subject of the email that will be sent to the recipients above.',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'site_form',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'seamless',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
		'show_in_rest' => 0,
	));