<?php

  $field_prefix = 'field_site_navigation_';
  $layout_prefix = 'layout_site_navigation_';
  
  acf_add_local_field_group(array(
    'key' => 'group_site_navigation',
    'title' => 'Navigation',
    'fields' => array(
      array(
        'key' => $field_prefix . 'items',
        'label' => 'Items',
        'name' => 'navigation_items',
        'type' => 'flexible_content',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'layouts' => array(
          ($layout_prefix . 'internal') => array(
            'key' => $layout_prefix . 'internal',
            'name' => 'internal',
            'label' => 'Internal',
            'display' => 'block',
            'sub_fields' => array(
              array(
                'key' => $field_prefix . 'internal_link',
                'label' => 'Link',
                'name' => 'link',
                'type' => 'page_link',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '50',
                  'class' => '',
                  'id' => '',
                ),
                'post_type' => ['page'],
                'taxonomy' => '',
                'allow_null' => 1,
                'allow_archives' => 1,
                'multiple' => 0,
              ),
              array(
                'key' => $field_prefix . 'internal_text',
                'label' => 'Text',
                'name' => 'text',
                'type' => 'text',
                'instructions' => '',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '50',
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
              ),
              array(
                'key' => $field_prefix . 'internal_secondary_navigation',
                'label' => 'Seconday navigation',
                'name' => 'secondary_navigation',
                'type' => 'select',
                'instructions' => 'Select "Automatic" to allow the system to create a secondary navigation for this page or "Custom" to define your own.',
                'required' => 1,
                'conditional_logic' => array(
                  array(
                    array(
                      'field' => $field_prefix . 'internal_render_as_button',
                      'operator' => '!=',
                      'value' => '1',
                    ),
                  ),
                ),
                'wrapper' => array(
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
                'choices' => array(
                  'no' => 'No',
                  'automatic' => 'Automatic',
                  'custom' => 'Custom',
                ),
                'default_value' => false,
                'allow_null' => 0,
                'multiple' => 0,
                'ui' => 0,
                'return_format' => 'value',
                'ajax' => 0,
                'placeholder' => '',
              ),
              array(
                'key' => $field_prefix . 'internal_secondary_navigation_items',
                'label' => 'Secondary navigation items',
                'name' => 'secondary_navigation_items',
                'type' => 'flexible_content',
                'instructions' => '',
                'required' => 1,
                'conditional_logic' => array(
                  array(
                    array(
                      'field' => $field_prefix . 'internal_secondary_navigation',
                      'operator' => '==',
                      'value' => 'custom',
                    ),
                  ),
                ),
                'wrapper' => array(
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
                'layouts' => array(
                  ($layout_prefix . 'internal_internal') => array(
                    'key' => $layout_prefix . 'internal_internal',
                    'name' => 'internal',
                    'label' => 'Internal',
                    'display' => 'block',
                    'sub_fields' => array(
                      array(
                        'key' => $field_prefix . 'internal_internal_link',
                        'label' => 'Link',
                        'name' => 'link',
                        'type' => 'page_link',
                        'instructions' => '',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                          'width' => '50',
                          'class' => '',
                          'id' => '',
                        ),
                        'post_type' => ['page'],
                        'taxonomy' => '',
                        'allow_null' => 0,
                        'allow_archives' => 1,
                        'multiple' => 0,
                      ),
                      array(
                        'key' => $field_prefix . 'internal_internal_text',
                        'label' => 'Text',
                        'name' => 'text',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                          'width' => '50',
                          'class' => '',
                          'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                      ),
                    ),
                    'min' => '',
                    'max' => '',
                  ),
                  ($layout_prefix . 'internal_external') => array(
                    'key' => $layout_prefix . 'internal_external',
                    'name' => 'external',
                    'label' => 'External',
                    'display' => 'block',
                    'sub_fields' => array(
                      array(
                        'key' => $field_prefix . 'internal_external_link',
                        'label' => 'Link',
                        'name' => 'link',
                        'type' => 'url',
                        'instructions' => '',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                          'width' => '50',
                          'class' => '',
                          'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                      ),
                      array(
                        'key' => $field_prefix . 'internal_external_text',
                        'label' => 'Text',
                        'name' => 'text',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                          'width' => '50',
                          'class' => '',
                          'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                      ),
                    ),
                    'min' => '',
                    'max' => '',
                  ),
                ),
                'button_label' => 'Add Item',
                'min' => '',
                'max' => '',
              ),
            ),
            'min' => '',
            'max' => '',
          ),
          ($layout_prefix . 'external') => array(
            'key' => $layout_prefix . 'external',
            'name' => 'external',
            'label' => 'External',
            'display' => 'block',
            'sub_fields' => array(
              array(
                'key' => $field_prefix . 'external_link',
                'label' => 'Link',
                'name' => 'link',
                'type' => 'url',
                'instructions' => '',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '50',
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
              ),
              array(
                'key' => $field_prefix . 'external_text',
                'label' => 'Text',
                'name' => 'text',
                'type' => 'text',
                'instructions' => '',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '50',
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
              ),
            ),
            'min' => '',
            'max' => '',
          ),
        ),
        'button_label' => 'Add Item',
        'min' => '',
        'max' => '',
      ),
    ),
    'location' => array(
      array(
        array(
          'param' => 'post_type',
          'operator' => '!=',
          'value' => 'page',
        ),
      ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'seamless',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => false,
    'description' => 'Generic',
    'show_in_rest' => 0,
  ));